# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6663a60015e58aa35c432142752c52247820cc50310e1f3e1958debcbb1a551bc5c5beec11598aa7fd407908fe647f590ece7857383ea495a831ae810a21108f

test:
  secret_key_base: d5a3c25678110bfbc8fb9d65067a7b6186933fe5ef798126d13511bdb8fd66e7106d7bc689a2bc6e1fa48720f148fab10e636b498af16acf76c07f6009bfd881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
